version: '2'
services:
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./:/app
        links:
            - database
            - cache
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "DB_DATABASE=dockerApp"
            - "DB_PASSWORD=secret"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
    database:
        image: mysql:latest
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=dockerApp"
        ports:
            - "33061:3306"
    cache:
        image: redis:3.0
        ports:
            - "63791:6379"